version: "3"

services:
    nginx:
        build: .docker/nginx/${NGINX_VERSION}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/var/www/html
    
    php:
        build: .docker/php/${PHP_VERSION}
        volumes:
            - ./src:/var/www/html

    db:
        image: ${DB_VERSION}
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: magento
            MYSQL_DATABASE: ${DATABASE}
        command: --default-authentication-plugin=mysql_native_password
            
    elasticsearch:
        image: elasticsearch:${ELASTICSEARCH_VERSION}
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - "discovery.type=single-node"
    
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
